#!/bin/sh

set -u
set -e

if [ $# -lt 1 ]; then
	echo USAGE: $0 \<SourceForge user name\> [tag]
	exit 1
fi

TAG=
if [ $# -gt 1 ]; then
	TAG=.$2
fi

BUILDDIR=$HOME/src/vnc.nightly/latest/files
PROJWEB=/home/project-web/turbovnc/htdocs/
SSHSERVER=$1,turbovnc@shell.sourceforge.net

if [ ! -d $BUILDDIR ]; then
	echo No nightly build to upload!
	exit 1
fi

echo Uploading build ...
chmod 644 $BUILDDIR/*
ssh $SSHSERVER create
rsync -rltv --delete $BUILDDIR/* $SSHSERVER:$PROJWEB/vnc.nightly$TAG

exit 0
